# Generated by Django 2.2.7 on 2019-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191207_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(max_length=250),
        ),
    ]
